name: CI/CD for AI Inpainting

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inpainting-api:latest, ${{ secrets.DOCKERHUB_USERNAME }}/inpainting-api:${{ github.sha }}

  deploy-to-cloud-run:
    name: Deploy to Google Cloud Run
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }} 

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: inpainting-api-service 
          image: ${{ secrets.DOCKERHUB_USERNAME }}/inpainting-api:latest 
          region: asia-northeast3
          memory: 2Gi
          cpu: 1
          flags: "--cpu-boost"

